import {Inter} from "next/font/google";
import "./globals.css";
import FooterPage from "./footer/page";
import Navbar from "./components/Navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "ozuna",
    description: "Generated by ozuna"
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body classname={
                inter.className
            }>
                <Navbar/> {children}
                <FooterPage/>
            </body>
        </html>
    );
}
